== Main goals

Here it implementation of test task:

Implement a command-line reverse polish notation (RPN) calculator using a language that you know well.

== Reasoning behind your technical choices, including architectural

Solution build on top of Java 8 and represented as command line application.
Application uses multi-layer architecture.
. I/O layer
Presented as implementation of two interfaces: CalculatorInputStream and CalculatorOutputStream. For console application there is implementation of this Streams base on Java System streams.
. Parser layer
This layer uses I/O layer to read input from user. Mail login represents in UserInputParser class. This class now aware about possible formats of input commands, it is just iterate over
all possible command formats and operands.
. Operations layer
Main interface in this OperationTemplate. This class leads inherited class provide required information about command structure: count of operands, positions on operands and position of
operation sign. To implement new operation needs only implement interface OperationTemplate and add this as Service Provider. To keep application architecture flexible and simple extendable
all operations uses by application as service provider.
. Arithmetic operations layer
Contains implementation of all arithmetic operations. Also based on service provider architecture.

== Trade-offs you might have made, anything you left out, or what you might do differently if you were to spend additional time on the project
Behind scene application uses stack for storing operands and current result.
As far stack it is:
 .. generic type and
 .. calculator can be used for different types of number
 .. Java compiler uses type erasure

We can use Stack as a generic container but arithmetic operation should be implemented for each supported type. Current implementation of calculator supports Integer and Float type as a operands.
But due type erasure interface com.asolod.operation.Operation contains overloaded methods for both types of operands.

Application delivery contains Unit tests that covers main use-cases. Also test com.asolod.CalculatorFloatIntegerTest covers case of switching types of operands.

== How to run
To run application simply run main class com.asolod.Main.

== Summary

Hope my solution looks fine J
